# Generated by Django 5.0.4 on 2024-04-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aprovados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dependants', models.IntegerField(default=0)),
                ('applicantincome', models.IntegerField(default=0)),
                ('coapplicatincome', models.IntegerField(default=0)),
                ('loanamt', models.IntegerField(default=0)),
                ('loanterm', models.IntegerField(default=0)),
                ('credithistory', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Feminino')], max_length=50)),
                ('married', models.CharField(choices=[('Yes', 'Sim'), ('No', 'Não')], max_length=50)),
                ('graduatededucation', models.CharField(choices=[('Graduate', 'Graduado'), ('Not_Graduate', 'Não Graduado')], max_length=50)),
                ('selfemployed', models.CharField(choices=[('Yes', 'Sim'), ('No', 'Não')], max_length=50)),
                ('area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurbano'), ('Urban', 'Urbano')], max_length=50)),
            ],
        ),
    ]
