# Generated by Django 5.0.4 on 2024-04-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aprovados',
            new_name='aprovado',
        ),
    ]
