# Generated by Django 5.0.4 on 2024-04-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_rename_aprovados_aprovado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('dependents', models.IntegerField()),
                ('applicantIncome', models.IntegerField()),
                ('coapplicantIncome', models.IntegerField()),
                ('loanAmount', models.IntegerField()),
                ('loan_Amount_Term', models.IntegerField()),
                ('credit_History', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('married', models.CharField(max_length=3)),
                ('education', models.CharField(max_length=20)),
                ('self_Employed', models.CharField(max_length=3)),
                ('property_Area', models.CharField(max_length=10)),
                ('resultado', models.CharField(max_length=10)),
            ],
        ),
    ]
